### PR TITLE
fix: tag arrangement problem

### LINKED ISSUE #859: [Bug] Multiple tags can cause problems with tag arrangement
### Version

_No response_

### Current Behavior

image

https://github.com/openai/whisper

image

https://github.com/opencv/opencv

Multiple tags can cause problems with tag arrangement, such as in the two repositories above.

### Expected Behavior

_No response_

### Environment

```markdown
- OS:
- Browser:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by Xsy41**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #859 

## Details
Moved the original label to the right column, filtered the labels with type `xxx-n` and n is not 0, we get rid of the children labels.

image

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Review by wxharry — APPROVED** [review]
LGTM. Nice work!

File: src/pages/ContentScripts/features/repo-sidebar-labels/view.tsx [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+  const meta_labels = labels.map((label) => (
+    <span
+      key={label.id} // use label.id as the key
+      id={label.id}
+      className="topic-tag topic-tag-link"
+    >
+      {label.name}
+    </span>
+  ));
```
Comment (tyn1998) [inline src/pages/ContentScripts/features/repo-sidebar-labels/view.tsx:38]: @Xsy41 Great jobs!

a small tip: lowerCamelCase is usually adopted by JavaScript/TypeScript projects, so `metaLabels` is preferred here compared to `meta_labels` :)

Comment (Xsy41) [reply src/pages/ContentScripts/features/repo-sidebar-labels/view.tsx:38]: Thanks for your advice! 😄 I will immediately change to `metaLabels` and follow the JavaScript/TypeScript style ~ Thanks for pointing out this little detail! 🎉 @tyn1998
