### PR TITLE
fix: all zeros problem

### LINKED ISSUE #595: [Bug] Activity, OpenRank, Participants become all 0
### Version

1.8.4
image

### Current Behavior

[Bug] Activity, OpenRank, Participants become all 0

https://github.com/Tencent/APIJSON
image

image

image
image

### Expected Behavior

Show correct numbers

### Environment

```markdown
- OS: MacOS Ventura 13.0 (22A8380)
- Browser: Chrome 109.0.5414.119 (Official Build) (arm64)
```

### Any additional comments?

_No response_

### LINKED ISSUE #632: [Bug] Components next to repo name cannot display data
### Version

_No response_

### Current Behavior

image
It displays 0.

### Expected Behavior

_No response_

### Environment

```markdown
- OS:Mac M1
- Browser:Chrome
```

### Any additional comments?

I check other repos, there's no data too.

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- fix #595 
- fix #632

## Details

- use `Date.prototype.setDate(0)` to decrease the month number by 1
- make the assumption that data of last month can be ready in the 2nd day of every month
- describe how we update data in README

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @frank-zsy, I changed the code so now only when the condition `now.getDate() > 1` is fulfilled does Hypercrx show the data of last month. This means the first day of every month is reserved for OpenDigger to export data.

Is that ok?

File: src/utils/data.ts [hunk 1]
```diff
@@ -21,7 +21,11 @@ export const generateDataByMonth = (originalData: any) => {
   });
   const oldestMonth = orderedMonths[0];
   const now = new Date();
-  now.setMonth(now.getMonth() - 1);
+  if (now.getDate() === 1) {
+    // data for last month is not ready in the first day of the month (#595)
+    now.setDate(0); // a way to let month - 1
+  }
+  now.setDate(0); // see issue #632
```
Comment (xgdyp) [inline src/utils/data.ts:28]: > The code you provided is written in JavaScript. It appears to be manipulating a Date object called "now".
> 
> The first if statement checks if the current day of the month is the first day. If it is, then the comment suggests that data for the previous month may not be ready yet. In this case, the code sets the day of the month to 0, which effectively sets the date to the last day of the previous month. This is a way to let the month roll back by one.
> 
> The second line of code sets the day of the month to 0 again. The comment suggests that this is related to issue #632, but without more context it's difficult to say what that issue is.
> 
> Overall, it seems that this code is manipulating the "now" Date object to ensure that it represents the last day of the previous month.

Comment (tyn1998) [reply src/utils/data.ts:28]: Exactly what I mean, with better expression!
