### PR TITLE
fix: Optimize Avatar Loading

### LINKED ISSUE #938: [Optimize] It is possible to optimise the logic used to load numerous contributor avatars.
### Description

Depending on the circumstances, we load the avatars first and then display them when there are numerous contributors. The fact that not every user's avatar is shown simultaneously makes this incredibly wasteful.

For instance, the page https://github.com/exelban/stats/pulse is currently awaiting the loading of all contributors' avatars, which may take several minutes depending on the networking performance.

Image

Image

Consider displaying the avatar while loading it concurrently to speed up the loading process.

### PR DESCRIPTION
**Pull request by Xsy41**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #938 

## Details
Each month, the top 15 most active developers are selected based on their activity data and added to a set. Then, only the avatars of these active developers are loaded, optimizing the avatar loading efficiency.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by Xsy41** [comment]
Here’s the revised version with all three examples included:

Stats: The number of loaded developer avatars decreased from 1673 to 550.
(https://github.com/exelban/stats)

Vue.js: The number of loaded developer avatars decreased from 6700 to 1700.
(https://github.com/vuejs/vue)

TensorFlow: The number of loaded developer avatars decreased from 1300 to 500.
(https://github.com/tensorflow/tensorflow)

**Comment by Xsy41** [comment]
Some test sites
	1.	https://github.com/tensorflow/tensorflow
	2.	https://github.com/freeCodeCamp/freeCodeCamp
	3.	https://github.com/Microsoft/vscode
	4.	https://github.com/facebook/react
	5.	https://github.com/docker/docker
	6.	https://github.com/twbs/bootstrap
	7.	https://github.com/kubernetes/kubernetes
	8.	https://github.com/vuejs/vue
	9.	https://github.com/flutter/flutter
	10.	https://github.com/nodejs/node
	11.	https://github.com/github/gitignore
	12.	https://github.com/elastic/elasticsearch

**Comment by wangyantong2000** [comment]
image
The date and image overlap.

File: src/pages/ContentScripts/features/repo-activity-racing-bar/RacingBar.tsx [hunk 1]
```diff
@@ -135,9 +171,9 @@ const RacingBar = forwardRef(
     return (
       <div className="hypertrons-crx-border">
         <Spin
-          spinning={loadedAvatars < contributors.length}
-          tip={`Loading avatars ${loadedAvatars}/${contributors.length}`}
-          style={{ maxHeight: 'none' }} // disable maxHeight to make the loading tip be placed in the center
+          spinning={isLoading || loadedAvatars < totalAvatars}
+          tip={`Loading ${currentMonth} avatars (${loadedAvatars}/${totalAvatars})`}
```
Comment (wangyantong2000) [inline src/pages/ContentScripts/features/repo-activity-racing-bar/RacingBar.tsx:175]: Add another configuration in both Chinese and English.Although it hasn't happened before either.

**Comment by wangyantong2000** [comment]
This loading is indeed much faster than before.

File: src/pages/ContentScripts/features/repo-activity-racing-bar/RacingBar.tsx (hunk 1 above)
Comment (Xsy41) [reply src/pages/ContentScripts/features/repo-activity-racing-bar/RacingBar.tsx:175]: ok

**Comment by Xsy41** [comment]
> image The date and image overlap.

In most cases, this date does not obstruct the data. It only blocks the view in rare instances. Additionally, the date is transparent and does not affect the visual experience. Do we need to reduce the size of the date icon or change its position?

**Comment by wangyantong2000** [comment]
> > image The date and image overlap.
> 
> In most cases, this date does not obstruct the data. It only blocks the view in rare instances. Additionally, the date is transparent and does not affect the visual experience. Do we need to reduce the size of the date icon or change its position?

Yes, you can make some changes
