### PR TITLE
fix: abnormal-width on text select

### LINKED ISSUE #624: [Bug] Abnormal width variation of OSS-GPT chat widget when selecting text in it.
### Version

1.8.6

### Current Behavior

When I want to select a piece of text, the width of OSS-GPT chat widget changes as I move the mouse.

https://user-images.githubusercontent.com/62098023/225647575-808805bc-fd6b-45b3-b8f9-10a728c7559d.mp4

### Expected Behavior

The width of OSS-GPT chat widget should  be variable only when its edge is selected.

### Environment

```markdown
- OS: Windows
- Browser: whatever
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by stealth-bombeer**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- fix #624 

## Details

The react-chat-widget has bug in itself for it's resizing props, may be because it had event listener all over the container, so we don't use the inbuilt property of resizing instead we use jquery to select the container and allow it resize only when the left border of the container is dragged we watch for mutations in the useeffect when the conversation container becomes active 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

N.A

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @stealth-bombeer, thank you for raising this PR. I will review it later when I have time so just take a break 😃.

Would you mind changing the "keyword" in the PR description?

image

**Review by wxharry — COMMENTED** [review]
LGTM. Nice work! @stealth-bombeer 

Is this also fix #620 or not? I could not reproduce the issue. So, we might need Lam to give it a test. @tyn1998

**Comment by stealth-bombeer** [comment]
> > No still #620 persists,once these changes are reviewed as they seems to be related I can start working on it 💯
> 
> That would be great. Appreciate it!
> 
> Meanwhile, i am not sure if the `react-chat-widget` project is still under maintenance, but I think you could help them or other developers encountered the same issue by showing how you solve it in their community. It would be a good start point to embrace open source community. 😄

Thanks @wxharry ,I think this would be a great start and will surely look after it 😄

**Comment by tyn1998** [comment]
Share with you an interesting find:

if a PR target branch name is as same as a local branch name(like this case), then `gh pr checkout 658` will substitue the local one (unexpectedly).

image

So we'd better always create a new branch on the base branch before working on it :)

**Comment by stealth-bombeer** [comment]
> Share with you an interesting find:
> 
> if a PR target branch name is as same as a local branch name(like this case), then `gh pr checkout 658` will substitue the local one (unexpectedly).
> 
> image
> 
> So we'd better always create a new branch on the base branch before working on it :)

Oops,i'll make the necessary changes and commit it again ....

**Comment by tyn1998** [comment]
That is not a big deal, don't worry :) 

BTW, as far as I know, you cannot change the PR branch name. That automatically closes a PR.

And I'm reviewing your code, I'll give you feedback soon.

File: src/pages/ContentScripts/features/oss-gpt/view.tsx [hunk 1]
```diff
@@ -35,6 +35,8 @@ const View = ({ theme, currentRepo, currentDocsName }: Props): JSX.Element => {
   const [inited, setInited] = useState(false);
   const [settings, setSettings] = useState(new Settings());
   const [history, setHistory] = useState<[string, string]>(['', '']);
+  // Toggle to allow resizing of the widget
+  const [resizable, setResizable] = useState(true);
```
Comment (tyn1998) [inline src/pages/ContentScripts/features/oss-gpt/view.tsx:39]: `resizable` doesn't need to be a React state. `setResizable` is never used.

Actually we can make the chat-widget always resizable so do not need an option to toggle it. Just make it as default, no `if else`.

File: src/pages/ContentScripts/features/oss-gpt/view.tsx [hunk 2]
```diff
@@ -93,6 +95,44 @@ const View = ({ theme, currentRepo, currentDocsName }: Props): JSX.Element => {
...
+        );
+      } else {
+        if (resizable) {
+          // if resizer exits we only add listeners to it when resizable is true
+          const conversationContainer = $('.rcw-conversation-container');
+          const conversationResizer = $('.rcw-conversation-resizer');
+          let isDragging = false;
+          let initialMouseX: number;
+          let initialWidth: number;
+          if (conversationResizer.length) {
```
Comment (tyn1998) [inline src/pages/ContentScripts/features/oss-gpt/view.tsx:114]: please use `exists` helper function instead.

File: src/pages/ContentScripts/features/oss-gpt/view.tsx [hunk 3]
```diff
@@ -105,6 +145,11 @@ const View = ({ theme, currentRepo, currentDocsName }: Props): JSX.Element => {
     return () => {
       // Later, you can stop observing
       observer.disconnect();
+
+      if ($('.rcw-conversation-resizer')) {
+        $('.rcw-conversation-resizer').off('mousedown');
+        $(document).off('mousemove mouseup');
```
Comment (tyn1998) [inline src/pages/ContentScripts/features/oss-gpt/view.tsx:151]: Will `.off` remove all listeners (including GitHub own listeners) for mousemove and mouseup?

Maybe you can move the listeners more accurately.

**Review by tyn1998 — CHANGES_REQUESTED** [review]
Hi @stealth-bombeer, thanks for your PR. It works good, yet can still be improved :)

I commented serveral lines of code. Besides, I'm wondering if it is necessary to put the code in a MutationObserver callback?

File: src/pages/ContentScripts/features/oss-gpt/view.tsx (hunk 1 above)
Comment (stealth-bombeer) [reply src/pages/ContentScripts/features/oss-gpt/view.tsx]: The reason why this needs to be placed in mutation callback is we watch for the changes in rcw-widget-container as this should be fired only when the conversation container is active

**Comment by stealth-bombeer** [comment]
hi @tyn1998 i've made all the changes as suggested by you in the recent commit  , ensures that the exact same functions that were added as event listeners are removed rather than relying jquery's default behaviour and created a helper function to check validity of selector

**Review by tyn1998 — CHANGES_REQUESTED** [review]
Hi @stealth-bombeer, I tried a cleaner way to implement our own resizer. What do you think? 

```typescript
import React, { useState, useEffect, useRef } from 'react';
import $ from 'jquery';
import {
  Widget,
  addResponseMessage,
  deleteMessages,
  toggleMsgLoader,
  toggleInputDisabled,
} from 'react-chat-widget';

import { getAnswer } from './service';
import './rcw.scss';
import exists from '../../../../helpers/exists';
import { getMessageByLocale } from '../../../../utils/utils';
import Settings, { loadSettings } from '../../../../utils/settings';

interface Props {
  theme: 'light' | 'dark';
  currentRepo: string;
  currentDocsName: string | null;
}

const displayWelcome = (repoName: string, locale: string) => {
  addResponseMessage(
    getMessageByLocale('OSS_GPT_welcome', locale).replace('%v', repoName)
  );
};

const displayNotAvailable = (repoName: string, locale: string) => {
  addResponseMessage(
    getMessageByLocale('OSS_GPT_notAvailable', locale).replace('%v', repoName)
  );
};

const View = ({ theme, currentRepo, currentDocsName }: Props): JSX.Element => {
  const [inited, setInited] = useState(false);
  const [settings, setSettings] = useState(new Settings());
  const [history, setHistory] = useState<[string, string]>(['', '']);
  const mouseDownX = useRef(0); // X position when mouse down
  const rcwWidth = useRef(0); // rcw width when mouse down

  useEffect(() => {
    const initSettings = async () => {
      const temp = await loadSettings();
      setSettings(temp);
      setInited(true);
    };
    if (!inited) {
      initSettings();
    }
  }, [inited, settings]);

  const subtitle = currentDocsName
    ? getMessageByLocale('OSS_GPT_subtitle', settings.locale).replace(
        '%v',
        currentRepo
      )
    : getMessageByLocale(
        'OSS_GPT_subtitle_notAvailable',
        settings.locale
      ).replace('%v', currentRepo);

  const handleNewUserMessage = async (newMessage: string) => {
    toggleMsgLoader();
    toggleInputDisabled();

    if (currentDocsName) {
      const answer = await getAnswer(currentDocsName, newMessage, history);
      addResponseMessage(answer);
      setHistory([newMessage, answer]); // update history
    } else {
      displayNotAvailable(currentRepo, settings.locale);
    }

    toggleMsgLoader();
    toggleInputDisabled();
  };

  useEffect(() => {
    // when repo changes
    deleteMessages(Infinity); // delete all messages after repo switching
    setHistory(['', '']); // clear history
    if (currentDocsName) {
      // if docs for current repo is available
      displayWelcome(currentRepo, settings.locale);
    } else {
      displayNotAvailable(currentRepo, settings.locale);
    }
  }, [settings, currentRepo, currentDocsName]);

  const handleMouseDown = (event: JQuery.MouseDownEvent) => {
    mouseDownX.current = event.clientX;
    rcwWidth.current = parseInt(
      $('#rcw-conversation-container').css('width'),
      10
    );
    $(document).on('mousemove', handleMouseMove);
    $(document).on('mouseup', handleMouseUp);
  };

  const handleMouseMove = (event: JQuery.MouseMoveEvent) => {
    $('#rcw-conversation-container').css(
      'width',
      `${rcwWidth.current - (event.clientX - mouseDownX.current)}px`
    );
  };

  const handleMouseUp = (event: JQuery.MouseUpEvent) => {
    $(document).off('mousemove', handleMouseMove);
    $(document).off('mouseup', handleMouseUp);
  };

  // we cannot change emoji-mart theme with an option, so we have to use MutationObserver and jquery to change the css
  useEffect(() => {
    // Select the node that will be observed for mutations
    const targetNode = $('div.rcw-widget-container')[0]!;
    // Options for the observer (which mutations to observe)
    const config = { attributes: true, childList: true, subtree: true };
    // Callback function to execute when mutations are observed
    const callback: MutationCallback = (mutationList, observer) => {
      // hacking code for resizer
      if (
        !exists('.rcw-conversation-resizer') &&
        exists('.rcw-conversation-container')
      ) {
        //we only add a resizer when there is no resizer and there is an active  conversation container
        const resizerDiv = $('<div>');
        resizerDiv.attr('class', 'rcw-conversation-resizer');
        resizerDiv.on('mousedown', handleMouseDown);
        $('#rcw-conversation-container').prepend(resizerDiv);
      }
      // hacking code for emoji-mart
      if (exists('section.emoji-mart')) {
        $('section.emoji-mart').addClass(`emoji-mart emoji-mart-${theme}`);
      }
    };
    // Create an observer instance linked to the callback function
    const observer = new MutationObserver(callback);
    // Start observing the target node for configured mutations
    observer.observe(targetNode, config);

    return () => {
      // Stop observing
      observer.disconnect();
    };
  }, []);

  return (
    <div className={theme}>
      <Widget
        title="OSS-GPT"
        subtitle={subtitle}
        emojis={true} // will be enabled after style is fine tuned for two themes
        handleNewUserMessage={handleNewUserMessage}
        showBadge={false}
        profileAvatar={chrome.runtime.getURL('main.png')}
      />
    </div>
  );
};

export default View;

```

File: src/pages/ContentScripts/features/oss-gpt/view.tsx [hunk 4]
```diff
@@ -92,8 +92,51 @@ const View = ({ theme, currentRepo, currentDocsName }: Props): JSX.Element => {
...
+            if (isDragging) {
+              console.log(document);
+              const mouseX = event.clientX;
+              const widthDiff = mouseX - initialMouseX;
+              conversationContainer.css(
+                'width',
+                `${initialWidth - widthDiff}px`
+              );
+            }
+          };
```
Comment (tyn1998) [inline src/pages/ContentScripts/features/oss-gpt/view.tsx:130]: if you add `console.log(anything)` in `handleMouseMove`, you will find the times of this function being called is doubled every time users click and drag. That slows the page noticeably.

File: src/pages/ContentScripts/features/oss-gpt/view.tsx [hunk 5]
```diff
@@ -92,8 +92,51 @@ const View = ({ theme, currentRepo, currentDocsName }: Props): JSX.Element => {
     // Options for the observer (which mutations to observe)
     const config = { attributes: true, childList: true, subtree: true };
     // Callback function to execute when mutations are observed
+    function exists(selector: JQuery<HTMLElement>) {
+      return $(selector).length > 0;
+    }
```
Comment (tyn1998) [inline src/pages/ContentScripts/features/oss-gpt/view.tsx:97]: We have an `exists` in codebase already :)

File: src/pages/ContentScripts/features/oss-gpt/view.tsx (hunk 4 above)
Comment (stealth-bombeer) [reply src/pages/ContentScripts/features/oss-gpt/view.tsx:130]: I think this is because a new listener is added every time the useEffect that contains the callback function is triggered.

**Comment by stealth-bombeer** [comment]
> Hi @stealth-bombeer, I tried a cleaner way to implement our own resizer. What do you think?
> 
> ```ts
> import React, { useState, useEffect, useRef } from 'react';
> import $ from 'jquery';
> import {
>   Widget,
>   addResponseMessage,
>   deleteMessages,
>   toggleMsgLoader,
>   toggleInputDisabled,
> } from 'react-chat-widget';
> 
> import { getAnswer } from './service';
> import './rcw.scss';
> import exists from '../../../../helpers/exists';
> import { getMessageByLocale } from '../../../../utils/utils';
> import Settings, { loadSettings } from '../../../../utils/settings';
> 
> interface Props {
>   theme: 'light' | 'dark';
>   currentRepo: string;
>   currentDocsName: string | null;
> }
> 
> const displayWelcome = (repoName: string, locale: string) => {
>   addResponseMessage(
>     getMessageByLocale('OSS_GPT_welcome', locale).replace('%v', repoName)
>   );
> };
> 
> const displayNotAvailable = (repoName: string, locale: string) => {
>   addResponseMessage(
>     getMessageByLocale('OSS_GPT_notAvailable', locale).replace('%v', repoName)
>   );
> };
> 
> const View = ({ theme, currentRepo, currentDocsName }: Props): JSX.Element => {
>   const [inited, setInited] = useState(false);
>   const [settings, setSettings] = useState(new Settings());
>   const [history, setHistory] = useState<[string, string]>(['', '']);
>   const mouseDownX = useRef(0); // X position when mouse down
>   const rcwWidth = useRef(0); // rcw width when mouse down
> 
>   useEffect(() => {
>     const initSettings = async () => {
>       const temp = await loadSettings();
>       setSettings(temp);
>       setInited(true);
>     };
>     if (!inited) {
>       initSettings();
>     }
>   }, [inited, settings]);
> 
>   const subtitle = currentDocsName
>     ? getMessageByLocale('OSS_GPT_subtitle', settings.locale).replace(
>         '%v',
>         currentRepo
>       )
>     : getMessageByLocale(
>         'OSS_GPT_subtitle_notAvailable',
>         settings.locale
>       ).replace('%v', currentRepo);
> 
>   const handleNewUserMessage = async (newMessage: string) => {
>     toggleMsgLoader();
>     toggleInputDisabled();
> 
>     if (currentDocsName) {
>       const answer = await getAnswer(currentDocsName, newMessage, history);
>       addResponseMessage(answer);
>       setHistory([newMessage, answer]); // update history
>     } else {
>       displayNotAvailable(currentRepo, settings.locale);
>     }
> 
>     toggleMsgLoader();
>     toggleInputDisabled();
>   };
> 
>   useEffect(() => {
>     // when repo changes
>     deleteMessages(Infinity); // delete all messages after repo switching
>     setHistory(['', '']); // clear history
>     if (currentDocsName) {
>       // if docs for current repo is available
>       displayWelcome(currentRepo, settings.locale);
>     } else {
>       displayNotAvailable(currentRepo, settings.locale);
>     }
>   }, [settings, currentRepo, currentDocsName]);
> 
>   const handleMouseDown = (event: JQuery.MouseDownEvent) => {
>     mouseDownX.current = event.clientX;
>     rcwWidth.current = parseInt(
>       $('#rcw-conversation-container').css('width'),
>       10
>     );
>     $(document).on('mousemove', handleMouseMove);
>     $(document).on('mouseup', handleMouseUp);
>   };
> 
>   const handleMouseMove = (event: JQuery.MouseMoveEvent) => {
>     $('#rcw-conversation-container').css(
>       'width',
>       `${rcwWidth.current - (event.clientX - mouseDownX.current)}px`
>     );
>   };
> 
>   const handleMouseUp = (event: JQuery.MouseUpEvent) => {
>     $(document).off('mousemove', handleMouseMove);
>     $(document).off('mouseup', handleMouseUp);
>   };
> 
>   // we cannot change emoji-mart theme with an option, so we have to use MutationObserver and jquery to change the css
>   useEffect(() => {
>     // Select the node that will be observed for mutations
>     const targetNode = $('div.rcw-widget-container')[0]!;
>     // Options for the observer (which mutations to observe)
>     const config = { attributes: true, childList: true, subtree: true };
>     // Callback function to execute when mutations are observed
>     const callback: MutationCallback = (mutationList, observer) => {
>       // hacking code for resizer
>       if (
>         !exists('.rcw-conversation-resizer') &&
>         exists('.rcw-conversation-container')
>       ) {
>         //we only add a resizer when there is no resizer and there is an active  conversation container
>         const resizerDiv = $('<div>');
>         resizerDiv.attr('class', 'rcw-conversation-resizer');
>         resizerDiv.on('mousedown', handleMouseDown);
>         $('#rcw-conversation-container').prepend(resizerDiv);
>       }
>       // hacking code for emoji-mart
>       if (exists('section.emoji-mart')) {
>         $('section.emoji-mart').addClass(`emoji-mart emoji-mart-${theme}`);
>       }
>     };
>     // Create an observer instance linked to the callback function
>     const observer = new MutationObserver(callback);
>     // Start observing the target node for configured mutations
>     observer.observe(targetNode, config);
> 
>     return () => {
>       // Stop observing
>       observer.disconnect();
>     };
>   }, []);
> 
>   return (
>     <div className={theme}>
>       <Widget
>         title="OSS-GPT"
>         subtitle={subtitle}
>         emojis={true} // will be enabled after style is fine tuned for two themes
>         handleNewUserMessage={handleNewUserMessage}
>         showBadge={false}
>         profileAvatar={chrome.runtime.getURL('main.png')}
>       />
>     </div>
>   );
> };
> 
> export default View;
> ```

This is great and I think this resolves all above issues @tyn1998 and I think my code is quite repetitive at certain instances :(

**Comment by tyn1998** [comment]
@stealth-bombeer your code taught me how to implement "drag to resize". That is of great value! If my implementation is good to you, you may push another commit to this branch and I'll merge this PR :)

**Comment by stealth-bombeer** [comment]
> @stealth-bombeer your code taught me how to implement "drag to resize". That is of great value! If my implementation is good to you, you may push another commit to this branch and I'll merge this PR :)

Thanks, I'll commit making the final changes

**Review by tyn1998 — APPROVED** [review]
LGTM, thank you so much @stealth-bombeer !
