### PR TITLE
feat: use meta.json to request smarter & fix wrong initialization timings of features

### LINKED ISSUE #571: [Feature] to use meta.json to decrease invalid network requests
### Description

reference: https://github.com/X-lab2017/open-digger/issues/1168

### LINKED ISSUE #688: [Bug] OSS-GPT only shows on Code tab
### Version

v1.9.0

### Current Behavior

I am not sure it is a bug or not. The OSS-GPT only shows when I am on the `code` tab. Did I miss the discussion about where to show the OSS-GPT?

### Expected Behavior

OSS-GPT is always there in a repository.

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [x] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #571 
- #635
- fix #688

## Details

In this PR, [meta.json](https://github.com/X-lab2017/open-digger/issues/1168) is introduced to decrease invalid network requests and to decide `lastDataAvailableMonth`.

meta.json examples:

- https://oss.x-lab.info/open_digger/github/tyn1998/meta.json (user meta)
- https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/meta.json (repo meta)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

File: src/helpers/get-repo-info.ts [hunk 1]
```diff
@@ -1,5 +1,33 @@
...
+/**
+ * check if the repository is public
+ */
+export async function isPublicRepo() {
+  const selector = 'meta[name="octolytics-dimension-repository_public"]';
+  await elementReady(selector);
+  // <meta name="octolytics-dimension-repository_public" content="true/false">
+  const isPublic = $(selector).attr('content') === 'true';
+  return pageDetect.isRepo() && isPublic;
+}
```
Comment (tyn1998) [inline src/helpers/get-repo-info.ts:29]: This three checkers will work in both the old and the new UI.

**Review by wxharry — APPROVED** [review]
LGTM. Thanks!
