### PR TITLE
fix: newestMonth should not be the last month in data files

### LINKED ISSUE #586: [Bug]  newestMonth should not be the last month in data files
### Version

1.8.3

### Current Behavior

I happened to visit https://github.com/X-lab2017/open-galaxy which is a long non-maintained repo and found that the `participant` is 6!

image

The cause is that we use the latest month in data files as `newestMonth` due to a wrong assumption: a repo should be active in every month.

https://github.com/hypertrons/hypertrons-crx/blob/6d06a8d54c70f38413941ac718625291478a2527/src/utils/data.ts#L23

### Expected Behavior

Maybe using the last month as `newestMonth` is the right way. For example, if the current month is Feburary, January should be the `newstMonth`.

### Environment

```markdown
- OS: whatever
- Browser: whatever
```

### Any additional comments?

This should be an easy task :)

### PR DESCRIPTION
**Pull request by wj23027**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- fix #586 

## Details

Replace the newestMonth with the last month, now it looks like:
image

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

File: src/utils/data.ts [hunk 1]
```diff
@@ -20,7 +20,9 @@ export const generateDataByMonth = (originalData: any) => {
     else return 0;
   });
   const oldestMonth = orderedMonths[0];
-  const newestMonth = orderedMonths[orderedMonths.length - 1];
+  const now = new Date();
+  const newestMonth =
+    now.getFullYear() + '-' + now.getMonth().toString().padStart(2, '0');
```
Comment (tyn1998) [inline src/utils/data.ts:25]: As pointed out in #568, we should use last month as `newestMonth` because if we are in 2023.1 only data of 2022.12 is available. All charts show data in last month.

The second mistake here is you might not know the truth that the value of Date.getMonth() [starts from 0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth).

**Review by tyn1998 — CHANGES_REQUESTED** [review]
Hi @wj23027, thank you for creating this PR. There are two places in the code should be corrected :)

**Review by tyn1998 — APPROVED** [review]
Have tested it. LGTM!

Thank you for your contribution!

/approve
